version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: setuptools
    versions:
    - 54.1.2
    - 54.1.3
    - 54.2.0
    - 56.0.0
  - dependency-name: pytest
    versions:
    - 6.2.3
  - dependency-name: twine
    versions:
    - 3.4.1
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
